/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ***REMOVED***.main;


import java.awt.Toolkit;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ***REMOVED***.util.DBUtil;
import ***REMOVED***.util.PasswordHash;


/**
 *
 * @author moon
 */
public class Market extends javax.swing.JFrame {

    private final String  permission;
    private final DBUtil ConsoleOP = new DBUtil();
    
    /**
     * Creates new form Market
     * @param ss
     *          传递的权限
     */
    public Market(String ss) {
        initComponents();
        //@moon:居中显示
        permission=ss;
        setLocationRelativeTo(null);      
        jPanel1.remove(jLabelWarning);
        //@moon:在这里“初始化”jTable
        clearStorage();
        clearInTable();
        //logintype
        //@moon:管理员权限判断
        
        if ("0".equals(permission)) {
            System.out.println("管理员");
            jPanel1.remove(img1);
        } else {
            jPanel1.removeAll();
            jPanel1.add(jLabelWarning);
            jPanel1.add(img1);
            jLabelWarning.setText("<html>你无权访问<br>这个页面！"
                    + "<br>我滑稽的<br>看着你(*@ο@*) <br>不信你点它看看</html>");

            jPanel2.remove(jTextField1);
            jPanel2.remove(jButton3);
            jPanel2.remove(jButton4);
            jPanel2.remove(jButton5);
            jPanel6.remove(jButton6);
            jPanel6.remove(jLabel2);
            jPanel6.remove(jLabel3);
            jPanel6.remove(jLabel4);
            jPanel6.remove(jTextReg);
            jPanel6.remove(jPasswdReg);
            jPanel6.remove(jCheckBox1);
            jPanel6.remove(jButton8);
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        img1 = new javax.swing.JLabel();
        jLabelWarning = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ar = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextReg = new javax.swing.JTextField();
        jPasswdReg = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabelHelp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("超市管理系统 - 滑稽版");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/moon/***REMOVED***/images/huaji.png")));
        setResizable(false);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "商品编号", "商品名", "生产商", "产地", "生产日期", "进价", "售价"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("插入记录");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moon/***REMOVED***/images/5.gif"))); // NOI18N
        img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img1MouseClicked(evt);
            }
        });

        jLabelWarning.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabelWarning.setForeground(new java.awt.Color(255, 0, 51));
        jLabelWarning.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("入库管理", jPanel1);

        ar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "商品编号", "商品称", "生产商", "产地", "生产日期", "进价", "售价"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ar);

        jButton2.setText("显示库存");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jTextField1.setText("请输入要查询的编号");

        jButton3.setText("修改信息");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("查询商品");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("删除商品");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel1.setText("超市目前共有商品多少件呢？");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton5)
                                .addGap(53, 53, 53)
                                .addComponent(jButton3))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("库存管理", jPanel2);

        jLabel2.setText("新增用户");

        jLabel3.setText("用户名");

        jLabel4.setText("密码");

        jButton6.setText("新增");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jCheckBox1.setText("是否为管理员？");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "用户角色", "用户名"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jButton7.setText("显示用户");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("删除用户");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextReg, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jPasswdReg))
                        .addGap(125, 125, 125)
                        .addComponent(jButton6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton7)
                        .addGap(111, 111, 111)
                        .addComponent(jButton8)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton6)))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswdReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("人员管理", jPanel6);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "程序说明", "开发者", "其实我才是开发者" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabelHelp.setFont(new java.awt.Font("华康少女文字W5", 0, 24)); // NOI18N
        jLabelHelp.setForeground(new java.awt.Color(0, 153, 0));
        jLabelHelp.setText("什么？你想干嘛？！");

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("系统说明", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 用空清空表
     */
    private void clearInTable() {
        //初始化jtable

        for (int i = 0; i <= jTable1.getRowCount() - 1; i++) {
            for (int j = 0; j < 7; j++) {
                jTable1.setValueAt("", i, j);
            }
        }
    }

    /**
     * 用空清空表
     */
    private void clearStorage() {

        for (int i = 0; i <= ar.getRowCount() - 1; i++) {
            for (int j = 0; j < 7; j++) {
                ar.setValueAt("", i, j);
            }
        }
    }
    
    
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
       //@moon:这里是最后搞笑的啦~~
        
        if (jComboBox1.getSelectedItem() == "程序说明") {
            jLabelHelp.setText("什么程序不程序的");           
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moon/***REMOVED***/images/4.gif")));
            jLabel5.setText("");
        }

        if (jComboBox1.getSelectedItem() == "开发者") {
            jLabelHelp.setText("我是开发者");         
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moon/***REMOVED***/images/yinxian.png")));
            jLabel5.setText("");
        }
        
        if (jComboBox1.getSelectedItem() == "其实我才是开发者") {
            jLabelHelp.setText("楼上不是开发者，Bunny - 小兔子 才是！");          
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moon/***REMOVED***/images/guai.png")));
            jLabel5.setText("");
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        //@moon:删除用户
        if (jButton8.isEnabled() == true) {
            if (jTable2.getValueAt(jTable2.getSelectedRow(), 0) == "管理员") {
                JOptionPane.showMessageDialog(null, "都是管理员，为何要相爱相杀", "爱即是恨", JOptionPane.ERROR_MESSAGE);
            } else {
                String SelUser = String.valueOf(jTable2.getValueAt(jTable2.getSelectedRow(), 1)).trim();
                String s = "delete  from admin  where aUser ='" + SelUser + "'";
                try {
                    ConsoleOP.OrdinaryQuery(s);
                    JOptionPane.showMessageDialog(null, "删除成功！", "信息", JOptionPane.YES_NO_OPTION);
                    DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
                    tableModel.removeRow(jTable2.getSelectedRow());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "删除失败！", "信息", JOptionPane.YES_NO_OPTION);
                    Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
  

    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // 显示用户jtable2
        jButton8.setEnabled(false);
        int i = 0;
        String s = "select * from admin ";
        ResultSet rs;
        try {
            rs = ConsoleOP.select(s);
            jButton8.setEnabled(true);
            while (rs.next()) {
                String aID = rs.getString(1);
                if (aID.equals("0")) {
                    aID = "管理员";
                } else {
                    aID = "普通用户";
                }
                String aUser = rs.getString(2);
                jTable2.setValueAt(aID, i, 0);
                jTable2.setValueAt(aUser, i, 1);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        try {                                      
            // 新增管理员
            //@moon:sha1
            //@moon:20170414 增加加盐散列
            //getSHA1 sha = new getSHA1();
            String regUname = jTextReg.getText().trim();
            String regPasswd = PasswordHash.createHash(jPasswdReg.getText().trim());
            String reg = null;
            if (jCheckBox1.isSelected()) {
                reg = "insert into admin values('0','" + regUname + "','" + regPasswd + "')";
            } else {
                reg = "insert into admin values('1','" + regUname + "','" + regPasswd + "')";
            }
            try {
                ConsoleOP.OrdinaryQuery(reg);
                JOptionPane.showMessageDialog(rootPane, "注册成功", "提示", WIDTH);
            } catch (SQLException ex) {
                Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "注册失败", "提示！", JOptionPane.YES_NO_OPTION);
            }
            
            jTextReg.setText("");
            jPasswdReg.setText("");
            
            
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeySpecException ex) {
            Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // 删除商品
        //删掉jTable中选定行

        if (ar.getValueAt(ar.getSelectedRow(), 0) == "") {
            JOptionPane.showMessageDialog(rootPane, "未选择", "错误", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            int n = JOptionPane.showConfirmDialog(this, "你要删除这条记录吗", "删除提示", JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION) //用户同意删除，在这里写入删除的代码！
            {
                //删除的sql语句
                String del = "delete  from product  where pID ='" + ar.getValueAt(ar.getSelectedRow(), 0) + "'";
                try {
                    ConsoleOP.OrdinaryQuery(del);
                    DefaultTableModel tableModel = (DefaultTableModel) ar.getModel();
                    tableModel.removeRow(ar.getSelectedRow());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex, "错误", JOptionPane.WARNING_MESSAGE);
                    Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // 查询指定商品
        //全部清空
        clearStorage();
        String inputID = jTextField1.getText().trim();
        String s = "select * from product  where pID ='" + inputID + "'";
        ResultSet specRs;
        try {
            specRs = ConsoleOP.select(s);
            if (specRs.next()) {
                //ID是唯一的主键，所以查询到一个就停了
                ar.setValueAt(specRs.getString(1), 0, 0);
                ar.setValueAt(specRs.getString(2), 0, 1);
                ar.setValueAt(specRs.getString(3), 0, 2);
                ar.setValueAt(specRs.getString(4), 0, 3);
                ar.setValueAt(specRs.getString(5), 0, 4);
                ar.setValueAt(specRs.getString(6), 0, 5);
                ar.setValueAt(specRs.getString(7), 0, 6);
            } else {
                JOptionPane.showMessageDialog(null, "您输入的编号不存在，请重新输入",
                    "输入错误", JOptionPane.YES_NO_OPTION);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField1.setText("请输入要查询的编号");

    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        //@moon:修改信息，这也是最困难的部分了
        //修改之前已经jTable已经有了内容了。所以就直接以ID为准每个都update
        //在这之前检测行尾
      
        String updateMainStr = null;
        for (int i = 0; i <= 99; i++) {
            if (ar.getValueAt(i, 0).toString() != "") {
                //横着读取，所以是00 01 02 03 04 05 06
                updateMainStr = "update product set pName='"
                    + ar.getValueAt(i, 1).toString().trim()
                    + "',pProducer='" + ar.getValueAt(i, 2).toString().trim()
                    + "',pOrigin='" + ar.getValueAt(i, 3).toString().trim()
                    + "',pDate='" + ar.getValueAt(i, 4).toString().trim()
                    + "',pPrice1='" + ar.getValueAt(i, 5).toString().trim()
                    + "',pPrice2='" + ar.getValueAt(i, 6).toString().trim()
                    + "' where pID='" + ar.getValueAt(i, 0).toString().trim() + "'";
                try {
                    //System.out.println(updateMainStr);
                    //数据库代码
                    ConsoleOP.OrdinaryQuery(updateMainStr);

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "修改失败", "信息", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                System.out.println("ID为空，似乎是空行了哦");
                JOptionPane.showMessageDialog(null, "修改成功！", "信息", JOptionPane.INFORMATION_MESSAGE);
                break;
            }
        }
   


    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // 显示全部的库存代码
        int i = 0;
        String count = "xx";
        String s = "select * from product ";
        ResultSet showProduct;
        try {
            showProduct = ConsoleOP.select(s);
            //商品有很多，所以要循环
            while (showProduct.next()) {
                ar.setValueAt(showProduct.getString(1), i, 0);
                ar.setValueAt(showProduct.getString(2), i, 1);
                ar.setValueAt(showProduct.getString(3), i, 2);
                ar.setValueAt(showProduct.getString(4), i, 3);
                ar.setValueAt(showProduct.getString(5), i, 4);
                ar.setValueAt(showProduct.getString(6), i, 5);
                ar.setValueAt(showProduct.getString(7), i, 6);
                i++;
            }
            count = "" + i + "";
            jLabel1.setText("超市现有商品" + count + "个");
        } catch (SQLException ex) {
            Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
        }

  
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // 入库管理，插入记录。
        //这次要做的是一次性添加多行的内容
        //首先就要确定用户输入了几行，以每一行的ID为准，循环获取。
        //jTable1.getValueAt(0, 0).toString();
        //inputLines=1是用户输入了一行。
        //jTable1.getValueAt(99, 0).toString();
       //debug 此处存在空
       
        int inputLines = 0;
        String[] a = new String[7];
      
        String insertStr = null;
        for (int i = 0; i <= 99; i++) {
            if (jTable1.getValueAt(i, 0).toString() != "") {
                inputLines++;
            }
        }
        
        //System.out.println(inputLines + " 多少行");
        //inputLines就是5行，数值为5
        
        if(inputLines==0)
            return;
        for (int i = 0; i < inputLines; i++) {
            a[0] = jTable1.getValueAt(i, 0).toString().trim();
            a[1] = jTable1.getValueAt(i, 1).toString().trim();
            a[2] = jTable1.getValueAt(i, 2).toString().trim();
            a[3] = jTable1.getValueAt(i, 3).toString().trim();
            a[4] = jTable1.getValueAt(i, 4).toString().trim();
            a[5] = jTable1.getValueAt(i, 5).toString().trim();
            a[6] = jTable1.getValueAt(i, 6).toString().trim();
            insertStr = "insert into product values('"
                + a[0] + "','" + a[1] + "','" + a[2] + "','" + a[3] + "','" + a[4] + "','"
                + a[5] + "','" + a[6] + "')";
           // System.out.println("SQL语句 " + insertStr);
            try {
                ConsoleOP.OrdinaryQuery(insertStr);
                               
            } catch (SQLException ex) {
                Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex, "出错了", JOptionPane.WARNING_MESSAGE);
            }
        }
        JOptionPane.showMessageDialog(null, "操作成功", "消息对话框", JOptionPane.WARNING_MESSAGE);
        clearInTable();
       

    }//GEN-LAST:event_jButton1MouseClicked

    private void img1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img1MouseClicked
        // 滑稽
        JOptionPane.showMessageDialog(rootPane, "谁让你点了？", "滑稽在此", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_img1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        //jPanel7.remove(jLabel5);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moon/***REMOVED***/images/2.gif")));
        jLabel5.setText("魔法变变变！");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        String str = null;
        ResultSet ShowRs1;
        ResultSet ShowRs2;
        if (jTabbedPane1.getSelectedIndex() == 1) {
            str = "select * from product ";
            try {
                ShowRs1 = ConsoleOP.select(str);
                int i = 0;
                while (ShowRs1.next()) {
                    ar.setValueAt(ShowRs1.getString(1), i, 0);
                    ar.setValueAt(ShowRs1.getString(2), i, 1);
                    ar.setValueAt(ShowRs1.getString(3), i, 2);
                    ar.setValueAt(ShowRs1.getString(4), i, 3);
                    ar.setValueAt(ShowRs1.getString(5), i, 4);
                    ar.setValueAt(ShowRs1.getString(6), i, 5);
                    ar.setValueAt(ShowRs1.getString(7), i, 6);
                    i++;
                }
            } catch (SQLException ex) {
                Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (jTabbedPane1.getSelectedIndex() == 2) {
            str = "select * from admin ";
            int i = 0;
            try {
                ShowRs2 = ConsoleOP.select(str);
                while (ShowRs2.next()) {
                    String aID = ShowRs2.getString(1);
                    if (aID.equals("0")) {
                        aID = "管理员";
                    } else {
                        aID = "普通用户";
                    }
                    String aUser = ShowRs2.getString(2);
                    jTable2.setValueAt(aID, i, 0);
                    jTable2.setValueAt(aUser, i, 1);
                    i++;
                }

            } catch (SQLException ex) {
                Logger.getLogger(Market.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Market.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Market(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ar;
    private javax.swing.JLabel img1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelHelp;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswdReg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextReg;
    // End of variables declaration//GEN-END:variables

    private void dbProduct() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
